server:
  port: 8086
  
spring:   
   application:   
      name:   dubbo-sentinel-demo-consumer

dubbo:   
   application:   
      name:   ${spring.application.name}
   registry:   
      address:   nacos://127.0.0.1:8848
   scan:   
      base-packages:   com.mydubbo



